import JotaiProvider from "@/components/jotaiProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NextAuthSessionProvider from "@/components/NextauthProvider";
import { Toaster } from "@/components/ui/toaster";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazir = localFont({
  src: [
    { path: "./webfonts/Vazirmatn-FD-Thin.woff2", weight: "100" },
    { path: "./webfonts/Vazirmatn-FD-Light.woff2", weight: "200" },
    { path: "./webfonts/Vazirmatn-FD-SemiBold.woff2", weight: "300" },
    { path: "./webfonts/Vazirmatn-FD-Regular.woff2", weight: "400" },
    { path: "./webfonts/Vazirmatn-FD-Medium.woff2", weight: "500" },
    { path: "./webfonts/Vazirmatn-FD-ExtraBold.woff2", weight: "600" },
    { path: "./webfonts/Vazirmatn-FD-Black.woff2", weight: "700" },
  ],
  variable: "--font-vazir",
  weight: "100 700",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vazir.className} antialiased`}
      >
        <NextAuthSessionProvider>
          <JotaiProvider>{children}
          </JotaiProvider>
        </NextAuthSessionProvider>
          <Toaster />
      </body>
    </html>
  );
}
